;; -*- scheme -*-

;; The vec type isn't used by the compiler anymore. Use boring void *
;; instead.
; xfail

;; A higher-level language for writing kernels. This was made by
;; lifting simple-kernel.sc. It should compile down to more or less
;; the same thing.

;; This is now being updated for the new vector representation.

((gpu-module
  (kernel simple ((X_ptr (ptr void)))
          (let X vec (vec_deserialize X_ptr))
          (let i int (get_global_id 0))
          (set! (deref (cast (ptr int) (vec_ref_1d X i)))
                (+ (deref (cast (ptr int) (vec_ref_1d X i))) 1))))
 
 (func int main ()
       (do ((field g_prog build)))
       
       (let X vec (mk_vec 1 4 (sizeof int)))
       (set! (deref (cast (ptr int) (vec_ref_1d X 0))) 1)
       (set! (deref (cast (ptr int) (vec_ref_1d X 1))) 2)
       (set! (deref (cast (ptr int) (vec_ref_1d X 2))) 3)
       (set! (deref (cast (ptr int) (vec_ref_1d X 3))) 4)

       (apply-kernel simple (var vec X))
       
       (do (print_int_vec X)
           (assert (= (deref (cast (ptr int) (vec_ref_1d X 0))) 2))
         (assert (= (deref (cast (ptr int) (vec_ref_1d X 1))) 3))
         (assert (= (deref (cast (ptr int) (vec_ref_1d X 2))) 4))
         (assert (= (deref (cast (ptr int) (vec_ref_1d X 3))) 5)))
       
       (print X)
       
       (return 0)))
