#!/bin/bash

if [ -z $SCHEME ];
then SCHEME=petite;
fi

schemeScript="$0".scm
HARLAN_DIR=`dirname $schemeScript`

case $SCHEME in
vicare)
        $SCHEME -L $HARLAN_DIR -L $HARLAN_DIR/external/nanopass-framework --more-file-extensions --r6rs-script "$schemeScript" -- -L $HARLAN_DIR/lib/harlan -R $HARLAN_DIR/rt $@
        ;;
petite | scheme | chez )
        dir=$HARLAN_DIR:external/nanopass-framework/lib/csv8.4/$MACHINE:$HARLAN_DIR/external/nanopass-framework
        $SCHEME --libdirs "$dir" --program "$schemeScript" -L $HARLAN_DIR/lib/harlan -R $HARLAN_DIR/rt $@
        ;;
scheme)
        dir=$HARLAN_DIR:external/nanopass-framework/lib/csv8.4/$MACHINE:$HARLAN_DIR/external/nanopass-framework
        scheme --compile-imported-libraries --libdirs "$dir" --program "$schemeScript" -L $HARLAN_DIR/lib/harlan -R $HARLAN_DIR/rt $@
        ;;
scheme)
        dir=$HARLAN_DIR:external/nanopass-framework/lib/csv8.4/$MACHINE:$HARLAN_DIR/external/nanopass-framework
        scheme --compile-imported-libraries --libdirs "$dir" --program "$schemeScript" -L $HARLAN_DIR/lib/harlan -R $HARLAN_DIR/rt $@
        ;;
*)
        echo $SCHEME is not a supported Scheme implementation
        ;;
esac

