(import (elegant-weapons compat)
        (elegant-weapons graphs)
        (elegant-weapons graphviz)
        (elegant-weapons helpers)
        (elegant-weapons insert-prototypes)
        (elegant-weapons match)
        (elegant-weapons print-c)
        (elegant-weapons record-case)
        (elegant-weapons sets)
        (nanopass))
